Repository benchttp/webapp, pull requests merged in 2022-02, with the labels that each got.

#11 Init codebase
  .gitignore
  .husky/pre-push
  .prettierignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/pages/counter/Counter.module.css
  src/pages/counter/Counter.tsx
  src/pages/counter/counterAPI.ts
  src/pages/counter/counterSlice.spec.ts
  src/pages/counter/counterSlice.ts
  src/react-app-env.d.ts
  src/routes/index.tsx
  src/setupTests.ts
  src/shared/hooks/store.ts
  src/shared/store.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: enhancement

#36 chore: replace deprecated tslint with eslint
  .eslintrc.yml
  .prettierrc.json
  config-overrides.js
  package.json
  src/components/Header/index.tsx
  src/components/Header/typescript/sidebar.styles.ts
  src/components/Header/typescript/sidebar.types.ts
  src/components/Sidebar/index.tsx
  src/components/Sidebar/typescript/sidebar.styles.ts
  src/components/Sidebar/typescript/sidebar.types.ts
  src/components/Text/index.tsx
  src/components/Text/typescript/text.stories.tsx
  src/components/Text/typescript/text.style.ts
  src/index.tsx
  src/layouts/MainLayout/index.tsx
  src/layouts/MainLayout/typescript/mainLayout.styles.ts
  src/pages/counter/Counter.tsx
  src/pages/counter/counterSlice.spec.ts
  src/pages/counter/counterSlice.ts
  src/routes/index.tsx
  src/routes/routes.constants.ts
  src/routes/routes.types.ts
  src/shared/hooks/store.ts
  src/shared/store.ts
  src/shared/style/constants.ts
  src/shared/style/index.ts
  tslint.json
  yarn.lock
Labels: enhancement

#42 feat: add PR and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: nice to have

#38 chore: add eslint rule no default export
  .eslintrc.yml
  src/components/Header/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Text/index.tsx
  src/components/Text/typescript/text.stories.tsx
  src/index.tsx
  src/layouts/MainLayout/index.tsx
  src/pages/Index/index.tsx
  src/pages/counter/counterSlice.ts
  src/routes/index.tsx
  src/routes/routes.constants.ts
Labels: nice to have

#44 fix: wrong paths from build
  .eslintrc.yml
  package.json
Labels: bug
